import type { Metadata } from "next";
import { ArrowUpRight, Compass, Handshake, Network, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { PageHero } from "@/components/site/page-hero";
import { buttonVariants } from "@/components/ui/button";

export const metadata: Metadata = { title: "Om oss", description: "Om IT Kompass AS og hvordan vi jobber som leverandøruavhengig IT- og telecompartner." };

export default function AboutPage() {
  return <main id="main">
    <PageHero eyebrow="Om oss" title="Én partner når IT og telecom skal henge sammen." body="IT Kompass AS er en nøytral partner for små og mellomstore bedrifter. Vi finner riktig løsning uavhengig av leverandør og følger opp helheten." />
    <section className="section-pad"><div className="container-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div className="grid size-16 place-items-center rounded-2xl border border-[#269BFF]/25 bg-[#269BFF]/10 text-[#6EC5FF]"><Compass size={27}/></div><p className="mt-7 text-2xl leading-9 tracking-[-.03em] text-slate-200">Kompasset er signaturen. Retningen kommer fra behovet ditt.</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="surface-card rounded-[1.4rem] p-6"><Handshake className="text-[#6EC5FF]"/><h2 className="mt-7 text-xl font-semibold">Nøytral rådgivning</h2><p className="mt-3 text-sm leading-6 text-slate-400">Vi starter med hva virksomheten skal oppnå og vurderer leverandører ut fra det.</p></article><article className="surface-card rounded-[1.4rem] p-6"><Network className="text-[#6EC5FF]"/><h2 className="mt-7 text-xl font-semibold">Helheten samlet</h2><p className="mt-3 text-sm leading-6 text-slate-400">WiFi, fiber, mobil, support og nettsider kan håndteres gjennom samme kontaktflate.</p></article><article className="surface-card rounded-[1.4rem] p-6"><ShieldCheck className="text-[#6EC5FF]"/><h2 className="mt-7 text-xl font-semibold">Forberedt for drift</h2><p className="mt-3 text-sm leading-6 text-slate-400">Løsninger skal være forståelige og mulige å følge opp også etter at prosjektet er ferdig.</p></article><article className="surface-card rounded-[1.4rem] p-6"><Compass className="text-[#6EC5FF]"/><h2 className="mt-7 text-xl font-semibold">Tydelig retning</h2><p className="mt-3 text-sm leading-6 text-slate-400">Vi skal gjøre det lettere å vite hva som bør gjøres først og hvorfor.</p></article></div></div></section>
    <section className="section-pad bg-[#050f1b]"><div className="container-shell rounded-[2rem] border border-white/10 bg-[#0a1828] p-8 sm:p-12"><div className="max-w-3xl"><div className="eyebrow">Arbeidsmåte</div><h2 className="section-title mt-5">Vi skal være en partner du kan ringe før problemet blir stort.</h2><p className="body-lg mt-6">Det betyr ryddig kommunikasjon, tydelig ansvar og løsninger som ikke gjør virksomheten mer avhengig av teknologien enn den trenger å være.</p><Link href="/kontakt" className={`${buttonVariants({ size: "lg" })} mt-8`}>Ta kontakt <ArrowUpRight size={18}/></Link></div></div></section>
  </main>;
}
